# Generated by Django 4.0.4 on 2022-12-17 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFileSets',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FileSetName', models.CharField(max_length=48)),
                ('Includes', models.CharField(max_length=256)),
                ('Excludes', models.CharField(max_length=256)),
                ('Compress', models.BooleanField(default=True)),
                ('Recursive', models.BooleanField(default=False)),
                ('EstimatedSize', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'basefilesets',
                'ordering': ['Includes'],
            },
        ),
        migrations.CreateModel(
            name='DeviceTypes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DeviceType', models.CharField(max_length=24)),
            ],
            options={
                'db_table': 'devicetypes',
                'ordering': ['DeviceType'],
            },
        ),
        migrations.CreateModel(
            name='FileSets',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FileSetName', models.CharField(max_length=48)),
                ('Includes', models.CharField(max_length=256)),
                ('Excludes', models.CharField(max_length=256)),
                ('Compress', models.BooleanField(default=True)),
                ('Recursive', models.BooleanField(default=False)),
                ('EstimatedSize', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'filesets',
                'ordering': ['FileSetName'],
            },
        ),
        migrations.CreateModel(
            name='Frequencies',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Frequency', models.CharField(max_length=48)),
            ],
            options={
                'db_table': 'frequencies',
            },
        ),
        migrations.CreateModel(
            name='LogLevels',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Loglevel', models.CharField(max_length=12)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RootPaths',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Root_Path', models.CharField(max_length=256)),
                ('Active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rootpaths',
                'ordering': ['ID'],
            },
        ),
        migrations.CreateModel(
            name='StorageSets',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('StorageSetName', models.CharField(max_length=48)),
                ('StoragePath', models.CharField(max_length=1024)),
                ('DevicePathID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupgui.devicetypes')),
            ],
            options={
                'db_table': 'storagesets',
                'ordering': ['StorageSetName'],
            },
        ),
        migrations.CreateModel(
            name='BackupSets',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('BackupSetName', models.CharField(max_length=48)),
                ('FileSetName', models.CharField(max_length=48)),
                ('Versions', models.IntegerField(default=1)),
                ('FrequencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupgui.frequencies')),
                ('StorageSetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupgui.storagesets')),
            ],
            options={
                'db_table': 'backupsets',
                'ordering': ['BackupSetName'],
            },
        ),
    ]
