# Generated by Django 4.1 on 2022-12-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backupgui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SomeNewTable",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("SomeCharField", models.CharField(max_length=12)),
            ],
            options={"db_table": "somenewtable", "ordering": ["ID"],},
        ),
    ]
