# Generated by Django 4.1 on 2022-12-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backupgui", "0002_somenewtable"),
    ]

    operations = [
        migrations.DeleteModel(name="SomeNewTable",),
    ]
