# Generated by Django 4.1 on 2022-12-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backupgui", "0004_delete_loglevels"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoggingLevels",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("LogLevel", models.CharField(max_length=12)),
                ("Active", models.BooleanField(default=False)),
            ],
            options={"db_table": "logginglevels", "ordering": ["ID"],},
        ),
    ]
